config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :wall
  resources :user_data
  resources :team_user
  resources :team
  resources :position
  resources :office_table
  resources :office
  resources :mark
  resources :role
  resources :user
  resources :company
  match "/css/:page", to: 'application#css', via: [:get]
  match "/js/:page", to: 'application#js', via: [:get]
  match "/js/lib/:page", to: 'application#js', via: [:get]
  match "/fonts/:page", to: 'application#fonts', via: [:get]
  match "/hr_statistic", to: 'application#hr_statistic', via: [:get]
  match "/offices", to: 'application#offices', via: [:get]
  match "/login", to: 'application#login', via: [:post]
  match "/registration", to: 'application#company_registration', via: [:post]
  match "/manage", to: 'application#company_manage', via: [:post]
  match "/manage_user", to: 'application#user_manage', via: [:post]
  match "/search_company", to: 'application#search_company', via: [:post]
  match "/search_user", to: 'application#search_user', via: [:post]
  match "/all_company", to: 'application#index', via: [:post]
  match "/add_user", to: 'application#add_user', via: [:post]
  match "/manage_office", to: 'application#manage_office', via: [:post]
  match "/search_office", to: 'application#search_office', via: [:post]
  match "/all_offices", to: 'application#all_offices', via: [:post]
  match "/add_office", to: 'application#add_office', via: [:post]
  match "/open_map", to: 'application#open_map', via: [:post]
  match "/save_map", to: 'application#save_map', via: [:post]
  match "/manage_personal", to: 'application#manage_personal', via: [:post]
  match "/search_personal", to: 'application#search_personal', via: [:post]
  match "/search_personal", to: 'application#search_personal', via: [:post]
  match "/add_personal", to: 'application#add_personal', via: [:post]

  match "/save_map", to: 'application#save_map', via: [:post]
  match "/exit", to: 'application#exit', via: [:get]
  match "/img/:page", to: 'application#img', via: [:get]
  match "/:page", to: 'application#main', via: [:get]
  root 'application#index'

end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/mark.rb
class Mark < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/office_table.rb
class OfficeTable < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_datum.rb
class UserDatum < ApplicationRecord
end

app/models/wall.rb
class Wall < ApplicationRecord
end

app/models/work_status.rb
class WorkStatus < ApplicationRecord
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:title, :body)
    end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office, local: true) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.title %></td>
        <td><%= office.body %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @office.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @office.body %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>