config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :wall
  resources :user_data
  resources :team_user
  resources :team
  resources :position
  resources :office_table
  resources :office
  resources :mark
  resources :role
  resources :user
  resources :company
  match "/css/:page", to: 'application#css', via: [:get]
  match "/js/:page", to: 'application#js', via: [:get]
  match "/js/lib/:page", to: 'application#js', via: [:get]
  match "/fonts/:page", to: 'application#fonts', via: [:get]
  match "/hr_statistic", to: 'application#hr_statistic', via: [:get]
  match "/offices", to: 'application#offices', via: [:get]
  match "/login", to: 'application#login', via: [:post]
  match "/registration", to: 'application#company_registration', via: [:post]
  match "/manage", to: 'application#company_manage', via: [:post]
  match "/manage_user", to: 'application#user_manage', via: [:post]
  match "/search_company", to: 'application#search_company', via: [:post]
  match "/search_user", to: 'application#search_user', via: [:post]
  match "/all_company", to: 'application#index', via: [:post]
  match "/add_user", to: 'application#add_user', via: [:post]
  match "/manage_office", to: 'application#manage_office', via: [:post]
  match "/search_office", to: 'application#search_office', via: [:post]
  match "/all_offices", to: 'application#all_offices', via: [:post]
  match "/add_office", to: 'application#add_office', via: [:post]
  match "/open_map", to: 'application#open_map', via: [:post]
  match "/save_map", to: 'application#save_map', via: [:post]
  match "/manage_personal", to: 'application#manage_personal', via: [:post]
  match "/search_personal", to: 'application#search_personal', via: [:post]
  match "/search_personal", to: 'application#search_personal', via: [:post]
  match "/add_personal", to: 'application#add_personal', via: [:post]

  match "/save_map", to: 'application#save_map', via: [:post]
  match "/exit", to: 'application#exit', via: [:get]
  match "/img/:page", to: 'application#img', via: [:get]
  match "/:page", to: 'application#main', via: [:get]
  root 'application#index'

end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/mark.rb
class Mark < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/office_table.rb
class OfficeTable < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_datum.rb
class UserDatum < ApplicationRecord
end

app/models/wall.rb
class Wall < ApplicationRecord
end

app/models/work_status.rb
class WorkStatus < ApplicationRecord
end

app/controllers/team_users_controller.rb
class TeamUsersController < ApplicationController
  before_action :set_team_user, only: [:show, :edit, :update, :destroy]

  # GET /team_users
  # GET /team_users.json
  def index
    @team_users = TeamUser.all
  end

  # GET /team_users/1
  # GET /team_users/1.json
  def show
  end

  # GET /team_users/new
  def new
    @team_user = TeamUser.new
  end

  # GET /team_users/1/edit
  def edit
  end

  # POST /team_users
  # POST /team_users.json
  def create
    @team_user = TeamUser.new(team_user_params)

    respond_to do |format|
      if @team_user.save
        format.html { redirect_to @team_user, notice: 'Team user was successfully created.' }
        format.json { render :show, status: :created, location: @team_user }
      else
        format.html { render :new }
        format.json { render json: @team_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_users/1
  # PATCH/PUT /team_users/1.json
  def update
    respond_to do |format|
      if @team_user.update(team_user_params)
        format.html { redirect_to @team_user, notice: 'Team user was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_user }
      else
        format.html { render :edit }
        format.json { render json: @team_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_users/1
  # DELETE /team_users/1.json
  def destroy
    @team_user.destroy
    respond_to do |format|
      format.html { redirect_to team_users_url, notice: 'Team user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_user
      @team_user = TeamUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_user_params
      params.require(:team_user).permit(:title, :body)
    end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/team_users/_form.html.erb
<%= form_with(model: team_user, local: true) do |form| %>
  <% if team_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_user.errors.count, "error") %> prohibited this team_user from being saved:</h2>

      <ul>
      <% team_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/team_users/edit.html.erb
<h1>Editing Team User</h1>

<%= render 'form', team_user: @team_user %>

<%= link_to 'Show', @team_user %> |
<%= link_to 'Back', team_users_path %>

app/views/team_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Users</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_users.each do |team_user| %>
      <tr>
        <td><%= team_user.title %></td>
        <td><%= team_user.body %></td>
        <td><%= link_to 'Show', team_user %></td>
        <td><%= link_to 'Edit', edit_team_user_path(team_user) %></td>
        <td><%= link_to 'Destroy', team_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team User', new_team_user_path %>

app/views/team_users/new.html.erb
<h1>New Team User</h1>

<%= render 'form', team_user: @team_user %>

<%= link_to 'Back', team_users_path %>

app/views/team_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @team_user.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @team_user.body %>
</p>

<%= link_to 'Edit', edit_team_user_path(@team_user) %> |
<%= link_to 'Back', team_users_path %>